formspree_form_id: formspree_form_id
name: lyons_code
title: lyons_code
description: A portfolio of cybersecurity knowledge
tags:
  - blog
  - cybersecurity
  - portfolio
  - infosec
  - resume
  - ""
show_hero: true
menu:
  - title: Home
    url: /
  - title: Write-Ups
    url: /
  - title: Projects
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: michaellyons@protonmail.com
disqus_username: ""
